# Generated by Django 4.2.3 on 2023-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_associated_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(verbose_name='Desconto %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor R$'),
        ),
    ]
