# Generated by Django 4.2.3 on 2023-08-20 08:48

from django.db import migrations, models
import image_admin.models.base_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Image Banner', max_length=25)),
                ('image_desktop', models.ImageField(upload_to='cover/banner/desktop', verbose_name='Image Desktop')),
                ('image_mobile', models.ImageField(null=True, upload_to='cover/banner/mobile', verbose_name='Image Mobile')),
            ],
            bases=(image_admin.models.base_model.BaseImageMIxin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonalizedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Image Personalized Service', max_length=25)),
                ('image_desktop', models.ImageField(upload_to='cover/personalized_service/desktop', verbose_name='Image Desktop')),
                ('image_mobile', models.ImageField(null=True, upload_to='cover/personalized_service/mobile', verbose_name='Image Mobile')),
            ],
            bases=(image_admin.models.base_model.BaseImageMIxin, models.Model),
        ),
    ]
