# Generated by Django 4.2.3 on 2023-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_banner', models.ImageField(upload_to='Back-end_lunettes/cover/banner/', verbose_name='Image Banner')),
            ],
        ),
    ]
