# Generated by Django 4.2.3 on 2023-08-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_banner_desktop',
            field=models.ImageField(upload_to='cover/banner/desktop', verbose_name='Image Banner Desktop'),
        ),
    ]
