# Generated by Django 4.2.3 on 2023-08-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('image_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_desktop',
            field=models.ImageField(upload_to='cover/desktop/banner', verbose_name='Image Desktop'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(null=True, upload_to='cover/mobile/banner', verbose_name='Image Mobile'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(default='Image Banner', max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='personalizedservice',
            name='image_desktop',
            field=models.ImageField(upload_to='cover/desktop/personalized_service', verbose_name='Image Desktop'),
        ),
        migrations.AlterField(
            model_name='personalizedservice',
            name='image_mobile',
            field=models.ImageField(null=True, upload_to='cover/mobile/personalized_service', verbose_name='Image Mobile'),
        ),
        migrations.AlterField(
            model_name='personalizedservice',
            name='name',
            field=models.CharField(default='Image Personalized Service', max_length=25, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name')),
                ('image_1', models.ImageField(upload_to='cover/product', verbose_name='Image 1')),
                ('image_2', models.ImageField(upload_to='cover/product', verbose_name='Image 2')),
                ('image_3', models.ImageField(upload_to='cover/product', verbose_name='Image 3')),
                ('related_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Related Product')),
            ],
        ),
    ]
