# Generated by Django 4.2.3 on 2023-07-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(default='Image Banner', max_length=25),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_banner',
            field=models.ImageField(upload_to='cover/banner/', verbose_name='Image Banner'),
        ),
    ]
