# Generated by Django 4.2.3 on 2023-07-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_admin', '0002_banner_name_alter_banner_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(default='Image Banner', max_length=25, unique=True),
        ),
    ]
