# Generated by Django 4.2.3 on 2023-08-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_admin', '0002_alter_banner_image_desktop_alter_banner_image_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='name',
        ),
    ]
