# Generated by Django 4.2.3 on 2023-08-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_admin', '0003_remove_imageproduct_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'verbose_name': 'Image Product', 'verbose_name_plural': 'Image Products'},
        ),
        migrations.AlterModelOptions(
            name='personalizedservice',
            options={'verbose_name': 'Personalized Service', 'verbose_name_plural': 'Personalized Services'},
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image_1_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image_1_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image_2_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image_2_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image_3_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image_3_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image_1',
            field=models.ImageField(height_field='image_1_height', upload_to='cover/product', verbose_name='Image 1', width_field='image_1_width'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image_2',
            field=models.ImageField(height_field='image_2_height', upload_to='cover/product', verbose_name='Image 2', width_field='image_2_width'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image_3',
            field=models.ImageField(height_field='image_3_height', upload_to='cover/product', verbose_name='Image 3', width_field='image_3_width'),
        ),
    ]
