# Generated by Django 4.2.3 on 2023-08-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_admin', '0004_alter_imageproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='image_1_height',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='image_1_width',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='image_2_height',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='image_2_width',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='image_3_height',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='image_3_width',
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image_1',
            field=models.ImageField(upload_to='cover/product', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image_2',
            field=models.ImageField(upload_to='cover/product', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image_3',
            field=models.ImageField(upload_to='cover/product', verbose_name='Image 3'),
        ),
    ]
