# Generated by Django 4.2.6 on 2023-10-20 22:17

from django.db import migrations, models
import image_admin.models.base_model


class Migration(migrations.Migration):

    dependencies = [
        ('image_admin', '0005_remove_imageproduct_image_1_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Image Carousel', max_length=25, verbose_name='Name')),
                ('image_carousel', models.ImageField(upload_to='cover/carousel', verbose_name='Image Carousel')),
            ],
            bases=(image_admin.models.base_model.BaseImageMIxin, models.Model),
        ),
    ]
