# Generated by Django 4.2.3 on 2023-07-31 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.CharField(blank=True, max_length=150, verbose_name='Accessories')),
                ('bridge', models.FloatField(verbose_name='Bridge')),
                ('front', models.FloatField(verbose_name='Front')),
                ('hast', models.FloatField(verbose_name='Hast')),
                ('height', models.FloatField(verbose_name='Height')),
                ('lens', models.CharField(max_length=32, verbose_name='Lens')),
                ('material', models.CharField(max_length=32, verbose_name='Material')),
                ('size', models.CharField(max_length=32, verbose_name='Size')),
                ('warranty', models.IntegerField(verbose_name='Warranty')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25, verbose_name='Product Name')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('description', models.TextField(verbose_name='Description')),
                ('valor', models.FloatField(verbose_name='Valor R$')),
                ('discount', models.IntegerField(default=0, verbose_name='Desconto %')),
                ('price', models.FloatField(verbose_name='Price')),
                ('is_new_colection', models.BooleanField(default=False, verbose_name='New Colection')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='Category')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.details', verbose_name='Detail')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Subcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
