# Generated by Django 4.2.3 on 2023-07-28 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(limit_choices_to=[
                                    2], null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.subcategory', verbose_name='Subcategory'),
        ),
    ]
