# Generated by Django 4.2.3 on 2023-08-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='accessories',
            field=models.CharField(blank=True, default='Estojo e flanela', max_length=150, verbose_name='Accessories'),
        ),
    ]
