# Generated by Django 4.2.3 on 2023-09-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_details_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(
                to='products.product', verbose_name='Related Products'),
        ),
    ]
