# Generated by Django 4.2.3 on 2023-08-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_featured_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured_product',
        ),
        migrations.AddField(
            model_name='product',
            name='featured_products',
            field=models.BooleanField(default=False),
        ),
    ]
