# Generated by Django 4.2.3 on 2023-08-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_details_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Product Name'),
        ),
    ]
