# Generated by Django 4.2.3 on 2023-07-28 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0003_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(limit_choices_to={
                                    2, 'category_id'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Subcategory'),
        ),
    ]
