# Generated by Django 4.2.3 on 2023-07-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_discount_alter_product_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(
                max_length=25, unique=True, verbose_name='Product Name'),
        ),
    ]
