# Generated by Django 4.2.3 on 2023-07-31 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0010_alter_product_price_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='Product',
            new_name='detail',
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Subcategory'),
        ),
    ]
